source.. = src/
output.. = bin/
bin.includes = .,\
               META-INF/,\
               lib/,\
               OSGI-INF/,\
               lib/commons-compress.jar,\
               lib/gluegen-rt.jar,\
               lib/gson.jar,\
               lib/jcef-api.jar,\
               lib/jcefmaven.jar,\
               lib/jogl-all.jar
